Repository pytorch/torchchat, pull requests merged in 2024-10, with the labels that each got.

#1242 Bump torchao to commit on 09-30-24
  .github/workflows/pull.yml
  docs/quantization.md
  install/.pins/torchao-pin.txt
  runner/aoti.cmake
  runner/et.cmake
  torchchat/utils/quantize.py
  torchchat/utils/scripts/install_utils.sh
Labels: CLA Signed

#1241 Add MPS Fallback to support torchtune Multimodal MPS
  torchchat.py
Labels: CLA Signed

#1245 Only show MPS Compile Warning if compile is attempted
  torchchat/cli/cli.py
Labels: CLA Signed

#1246 Update quantization.md
  docs/quantization.md
Labels: CLA Signed

#1247 Fix non-MM multiturn: Use legacy formatting
  torchchat/usages/openai_api.py
Labels: CLA Signed

#1248 Absorb non-MM OpenAI dialog parsing into generic input parsing
  torchchat/generate.py
  torchchat/usages/openai_api.py
Labels: CLA Signed

#1227 [Distributed] create model on meta device
  dist_run.py
  torchchat/distributed/dtensor_utils.py
  torchchat/distributed/safetensor_utils.py
Labels: CLA Signed

#1254 [Distributed] Fix new token's shape
  dist_run.py
Labels: CLA Signed

#1243 Update multimodal.md to remove MPS message
  docs/multimodal.md
Labels: CLA Signed

#1258 Move .lintrunner.toml to top-level directory and include basic linting instructions in CONTRIBUTING.md
  .lintrunner.toml
  CONTRIBUTING.md
Labels: CLA Signed

#1256 [Easy] Remove unused variable and comments
  torchchat/generate.py
Labels: CLA Signed

#1257 [Distributed] Fix tiktokenizer decoding
  dist_run.py
  torchchat/distributed/safetensor_utils.py
Labels: CLA Signed

#1265 Lint generate.py and openai_api
  torchchat/generate.py
  torchchat/usages/openai_api.py
Labels: CLA Signed

#1255 Safetensors
  torchchat/cli/convert_hf_checkpoint.py
  torchchat/cli/download.py
  torchchat/model_config/model_config.py
Labels: enhancement, CLA Signed

#1270 Multiturn mm single image
  torchchat/generate.py
  torchchat/usages/browser.py
  torchchat/usages/openai_api.py
Labels: CLA Signed

#1266 [Distributed] add TokenizerType enum, spelling
  dist_run.py
Labels: CLA Signed

#1274 Flag misnomer: GeneratorArgs.is_torchtune_model
  torchchat/generate.py
Labels: CLA Signed

#1272 LLaMA 2 Chat Formatter List Message Content Fix
  torchchat/generate.py
  torchchat/usages/openai_api.py
Labels: CLA Signed

#1279 Add check for rocminfo in the installation script to replace the nightly URL with the appropriate ROCm whl.
  install/install_requirements.sh
Labels: CLA Signed, module: rocm, ciflow/rocm

#1268 [Distributed] Add support for torchchat checkpoint format
  dist_run.py
  torchchat/cli/builder.py
  torchchat/distributed/checkpoint_utils.py
Labels: CLA Signed

#1275 [Distributed] Support index + multi-bin loading
  torchchat/distributed/checkpoint_utils.py
Labels: CLA Signed

#1282 remove duplicated quantize_config vs cli priority logic from quantize.py
  torchchat/utils/quantize.py
Labels: CLA Signed

#1259 Bias tensors
  torchchat/cli/convert_hf_checkpoint.py
  torchchat/model.py
Labels: CLA Signed

#1269 Pin Bump PT 20241002; Pin Bump ET to one using that PT pin
  CMakeLists.txt
  install/.pins/et-pin.txt
  install/.pins/torchao-pin.txt
  install/install_requirements.sh
  runner/et.cmake
  torchchat/export.py
Labels: CLA Signed

#1260 Tied word embeddings
  torchchat/model.py
Labels: CLA Signed

#1287 Add Initial Compile for Llama 3.2 11B: Decoder TransformerSelfAttentionLayer, TransformerCrossAttentionLayer
  torchchat/generate.py
Labels: CLA Signed

#1288 Android artifact update to 241002
  README.md
  torchchat/utils/scripts/android_example.sh
Labels: CLA Signed

#1290 [Android] Download prebuilt sha256sums from URL
  README.md
  torchchat/utils/scripts/android_example.sh
Labels: CLA Signed

#1294 Update Android app path
  torchchat/utils/scripts/android_example.sh
Labels: CLA Signed

#1295 Push Message formatting into _gen_model_input
  torchchat/generate.py
Labels: CLA Signed

#1301 Remove numpy < 2.0 pin to align with pytorch
  install/requirements.txt
Labels: CLA Signed

#1300 Update torchtune pin to 0.4.0.dev20241010
  install/install_requirements.sh
Labels: CLA Signed

#1307 Unbreak gguf util CI job by fixing numpy version
  install/requirements.txt
Labels: CLA Signed

#1305 Remove apparently-unused import torchvision in model.py
  torchchat/model.py
Labels: CLA Signed

#1314 [downloads] remove obsolete hf param for using symlinks (local_dir_use_symlinks=False,) and avoid showing warning about it
  torchchat/cli/download.py
Labels: CLA Signed

#1309 Detect unmatched skip begin/end commands
  .ci/scripts/run-docs
  torchchat/utils/scripts/updown.py
Labels: CLA Signed

#1308 Minor cleanup in torchchat/cli/builder.py
  torchchat/cli/builder.py
Labels: CLA Signed

#1299 Fix dangling open skip in README.md
  README.md
Labels: CLA Signed

#1317 Update Android screenshot
  README.md
Labels: CLA Signed

#1320 Add a redirect from pytorch/torchchat to the github repo
  .nojekyll
  index.html
Labels: documentation, CLA Signed

#1291 Implement the AO API in torchchat quantization handlers and unify logic.
  torchchat/utils/quantize.py
Labels: CLA Signed, Quantization

#1318 bump torchao pin
  .github/workflows/pull.yml
  docs/quantization.md
  install/.pins/torchao-pin.txt
  torchchat/utils/quantize.py
  torchchat/utils/scripts/install_utils.sh
Labels: CLA Signed

#1322 raise error with non-existence image prompts
  assets/view.jpg
  torchchat/generate.py
Labels: CLA Signed

#1331 Add docstrings build_utils.py, enforce consistent precision answers over a single run
  torchchat/utils/build_utils.py
Labels: CLA Signed

#1326 lm_eval: fix links and pin version
  install/requirements.txt
  torchchat/utils/docs/evaluation.md
Labels: CLA Signed

#1324 Update quantization.md
  docs/quantization.md
Labels: CLA Signed

#1330 Remove if statement preventing tps stats from being printed when running generate with compile
  torchchat/generate.py
Labels: CLA Signed
