Repository pytorch/torchchat, pull requests merged in 2024-11, with the labels that each got.

#896 Update packaging in AOTI path
  .ci/scripts/validate.sh
  .github/workflows/pull.yml
  .github/workflows/runner-cuda-dtype.yml
  README.md
  runner/run.cpp
  torchchat/cli/builder.py
  torchchat/cli/cli.py
  torchchat/export.py
  torchchat/generate.py
  torchchat/usages/eval.py
  torchchat/utils/build_utils.py
Labels: CLA Signed

#1340 add slack channel to readme
  README.md
Labels: CLA Signed

#1261 Tokenizers tokenizer
  tokenizer/base.py
  tokenizer/hf_tokenizer.py
  tokenizer/tiktoken.py
  torchchat/cli/builder.py
  torchchat/model.py
Labels: CLA Signed

#1343 Minor fixes to PT2 export path: enum typo and max_seq_len
  torchchat/export.py
  torchchat/utils/build_utils.py
Labels: CLA Signed

#1337 [AOTI] Remove the original model weights in Python deployment
  torchchat/cli/builder.py
Labels: CLA Signed

#1348 Minor code cleanups in generate.py and model.py
  torchchat/generate.py
  torchchat/model.py
Labels: CLA Signed

#1349 Fast non-model CLI commands
  torchchat/cli/cli.py
  torchchat/cli/convert_hf_checkpoint.py
  torchchat/utils/build_utils.py
Labels: CLA Signed

#1342 Fix error: characters can not be displayed normally in chinese
  torchchat/usages/openai_api.py
Labels: bug, CLA Signed, Browser

#1354 Update contributor channel name
  README.md
Labels: CLA Signed

#1345 fix: enforce python version
  install/install_requirements.sh
Labels: bug, CLA Signed

#1353 Remove last references to use_distributed argument
  torchchat/cli/builder.py
  torchchat/generate.py
Labels: CLA Signed

#1339 tokenizer was missing an include
  tokenizer/base64.h
Labels: CLA Signed

#1352 fix: add SIGINT handler
  torchchat.py
Labels: CLA Signed

#1359 Update cli.py to make --device/--dtype pre-empt quantize dict-specified values
  torchchat/cli/cli.py
Labels: CLA Signed

#1369 Update Caching logic to only trigger on the first inference sample
  torchchat/generate.py
Labels: CLA Signed

#1368 Minor typo + Update install_requirements.sh to support python 3.10 >=
  install/install_requirements.sh
Labels: CLA Signed

#1371 fix: remove dup dependency
  install/requirements.txt
Labels: CLA Signed

#1374 Bug Fix: Check for explicit cli device (fast)
  torchchat/cli/cli.py
Labels: CLA Signed

#1375 fix: do not print perf stat when NaN
  torchchat/generate.py
Labels: CLA Signed

#1372 fix: mark model argument as mandatory
  torchchat/cli/download.py
Labels: CLA Signed

#1378 Remove tokens per sec in aggregate_metrics when jit_compile
  torchchat/generate.py
Labels: CLA Signed

#1366 Download fix
  torchchat/cli/convert_hf_checkpoint.py
  torchchat/cli/download.py
Labels: CLA Signed

#1387 Clarify messages in builder.py
  torchchat/cli/builder.py
Labels: CLA Signed

#1382 Add multimodal to possible tests
  .ci/scripts/run-docs
  .github/workflows/run-readme-pr.yml
  docs/multimodal.md
Labels: CLA Signed

#1386 Fix English language usage in Runtime exception for builder.py
  torchchat/cli/builder.py
Labels: CLA Signed

#1377 Bug fix: Enable fast to override quantize json
  torchchat/cli/cli.py
Labels: CLA Signed

#1390 Changing the referenced AAR so that it uses the AAR from the docs
  .gitignore
  torchchat/edge/android/torchchat/app/build.gradle.kts
Labels: bug, CLA Signed, Mobile - Android, ExecuTorch

#1394 Typo fixes in native-execution.md
  docs/native-execution.md
Labels: CLA Signed

#1393 Improvements for readability in ADVANCED-USERS.md
  docs/ADVANCED-USERS.md
Labels: CLA Signed

#1391 Update multimodal.md to exercise server as part of test
  docs/multimodal.md
Labels: CLA Signed, Llama 3.2- Multimodal
