Repository pytorch/torchchat, pull requests merged in 2024-12, with the labels that each got.

#1392 Update quantization.md link to quantize.py
  docs/quantization.md
Labels: CLA Signed

#1400 Bump torch pin to 20241010
  .github/workflows/pull.yml
  install/.pins/et-pin.txt
  install/install_requirements.sh
Labels: CLA Signed

#1407 Update PT Pin to 1013
  install/install_requirements.sh
Labels: CLA Signed

#1405 Update docs for max-autotune usage
  docs/ADVANCED-USERS.md
  docs/model_customization.md
Labels: CLA Signed

#1403 Update run-docs to include `run-docs native`
  .ci/scripts/run-docs
  .github/workflows/run-readme-pr.yml
Labels: CLA Signed

#1384 Update README.md to run and query server during test
  .github/workflows/run-readme-pr-mps.yml
  README.md
Labels: CLA Signed

#1383 Update run-docs to enable `run-docs evaluation`
  .ci/scripts/run-docs
  torchchat/utils/docs/evaluation.md
Labels: CLA Signed

#1412 Formatting in README.md
  README.md
Labels: CLA Signed

#1411 Update evaluation.md to include AOTI
  torchchat/utils/docs/evaluation.md
Labels: CLA Signed

#1396 Update ADVANCED-USERS.md
  docs/ADVANCED-USERS.md
Labels: CLA Signed

#1418 Avoid curl fails due to server startup time
  README.md
Labels: CLA Signed

#1415 Add torchao mps ops
  .github/workflows/pull.yml
  docs/quantization.md
  install/.pins/torchao-pin.txt
  torchchat/utils/quantize.py
  torchchat/utils/scripts/build_torchao_ops.sh
  torchchat/utils/scripts/install_utils.sh
Labels: CLA Signed

#1367 Multi Pin Bumps across PT/AO/tune/ET
  .github/workflows/more-tests.yml
  .github/workflows/periodic.yml
  .github/workflows/pull.yml
  .github/workflows/run-readme-periodic.yml
  .github/workflows/run-readme-pr.yml
  .github/workflows/runner-cuda-dtype.yml
  install/.pins/torchao-pin.txt
  install/install_requirements.sh
  torchchat/cli/builder.py
  torchchat/distributed/checkpoint.py
  torchchat/utils/gguf_loader.py
Labels: CLA Signed

#1404 Update int4pack related in torchchat gguf
  torchchat/utils/gguf_loader.py
Labels: CLA Signed, Quantization

#1428 update torchao pin: optimized mps lowbit shaders
  install/.pins/torchao-pin.txt
  torchchat/utils/quantize.py
Labels: CLA Signed, Quantization

#1426 Update install_requirements.sh to tune + pt/pt dev20241218
  install/install_requirements.sh
Labels: CLA Signed, Llama 3.2- Multimodal, CI Infra, torchtune

#1336 Granite code support
  install/requirements.txt
  tests/conftest.py
  tests/test_chat_formatters.py
  tokenizer/hf_tokenizer.py
  torchchat/cli/cli.py
  torchchat/generate.py
  torchchat/model.py
  torchchat/model_config/models.json
  torchchat/model_params/Granite-3B-Code.json
  torchchat/model_params/Granite-8B-Code.json
Labels: CLA Signed

#1381 Integrate distributed inference with chat/server
  torchchat/cli/builder.py
  torchchat/distributed/checkpoint_utils.py
  torchchat/distributed/dist_run.py
  torchchat/distributed/generate.py
  torchchat/distributed/utils.py
  torchchat/generate.py
  torchchat/usages/openai_api.py
  torchchat/usages/server.py
Labels: CLA Signed

#1432 Granite 3.0 / 3.1 dense support
  torchchat/model.py
  torchchat/model_config/models.json
  torchchat/model_params/Granite-3.0-2B-Instruct.json
  torchchat/model_params/Granite-3.0-8B-Instruct.json
  torchchat/model_params/Granite-3.1-2B-Instruct.json
  torchchat/model_params/Granite-3.1-8B-Instruct.json
Labels: CLA Signed

#1434 Fix language in quantize.py
  torchchat/utils/quantize.py
Labels: CLA Signed

#1437 Update sh -> bash in quantization.md
  docs/quantization.md
Labels: CLA Signed

#1421 Output explicit selection of /bin/bash as interpreter for test scripts generated from .md with updown.py
  torchchat/utils/scripts/updown.py
Labels: CLA Signed

#1441 Fix how stream flag is read from request
  torchchat/usages/openai_api.py
Labels: CLA Signed
