Repository pytorch/torchchat, pull requests merged in 2025-01, with the labels that each got.

#1448 Create local-model.md
  docs/local-model.md
Labels: CLA Signed

#1442 Update evaluation.md
  torchchat/utils/docs/evaluation.md
Labels: CLA Signed

#1159 [aoti] Remove need for -l in cmake call
  .github/workflows/runner-cuda-dtype.yml
  README.md
  runner/run.cpp
  torchchat/export.py
Labels: CLA Signed

#1459 Bumping ET Pin to Jan16 2025
  .github/workflows/more-tests.yml
  .github/workflows/periodic.yml
  .github/workflows/pull.yml
  .github/workflows/run-readme-periodic.yml
  .github/workflows/run-readme-pr-mps.yml
  .github/workflows/run-readme-pr.yml
  .github/workflows/runner-cuda-dtype.yml
  install/.pins/et-pin.txt
  torchchat/export.py
Labels: CLA Signed, ExecuTorch

#1461 Fix quantize.py typo
  torchchat/utils/quantize.py
Labels: CLA Signed

#1460 Update run-readme-pr-mps.yml for typo
  .github/workflows/run-readme-pr-mps.yml
Labels: CLA Signed

#1361 Add Intel XPU device support to generate and serve
  install/install_requirements.sh
  torchchat/cli/builder.py
  torchchat/cli/cli.py
  torchchat/generate.py
  torchchat/utils/build_utils.py
  torchchat/utils/device_info.py
  torchchat/utils/quantize.py
Labels: CLA Signed

#1350 Create run-readme-pr-linuxaarch64
  .github/workflows/run-readme-pr-linuxaarch64.yml
  docs/ADVANCED-USERS.md
Labels: CLA Signed

#1451 Update run-readme-pr-mps.yml to fix timeout
  .github/workflows/run-readme-pr-mps.yml
Labels: CLA Signed

#1468 Add warning in PTEModel when not defined
  torchchat/model.py
Labels: CLA Signed

#1456 Add attention_backend to let user choose
  torchchat/cli/builder.py
  torchchat/cli/cli.py
  torchchat/generate.py
Labels: CLA Signed

#1470 Update import of sdpa_with_kv_cache to custom_ops
  torchchat/model.py
Labels: CLA Signed

#1471 Typo: Fix generate signature type hint for attention_backend
  torchchat/generate.py
Labels: CLA Signed

#1447 Change role to user for user prompts
  torchchat/generate.py
Labels: CLA Signed

#1469 Update run-readme-pr-linuxaarch64.yml to use correct runner
  .github/workflows/run-readme-pr-linuxaarch64.yml
Labels: CLA Signed

#1462 Increment start_pos by encoded size in generate
  torchchat/generate.py
Labels: CLA Signed

#1475 Explicitly turning off pybindings for ExecuTorch install unless requested
  torchchat/utils/scripts/install_utils.sh
Labels: CLA Signed, ExecuTorch

#1464 Replace RMSNorm by nn.RMSNorm
  install/install_requirements.sh
  torchchat/model.py
Labels: CLA Signed

#1455 Update aoti calls to utilize new export and packaging APIs
  torchchat/cli/builder.py
  torchchat/export.py
Labels: CLA Signed, Compile / AOTI

#1479 Update numpy requirements to no longer upper bound on 2.0
  install/requirements.txt
Labels: CLA Signed

#1409 Add evaluation, multimodal, native tests to run-readme-pr-macos.yml
  .github/workflows/run-readme-pr-macos.yml
Labels: CLA Signed

#1410 Add evaluation, multimodal, native tests to run-readme-pr-mps.yml
  .github/workflows/run-readme-pr-mps.yml
Labels: CLA Signed

#1417 bandaid for run-readme-pr-macos.yml incorrectly loading to MPS
  .github/workflows/run-readme-pr-macos.yml
Labels: CLA Signed

#1466 Add distributed tests to run-readme-pr.yml
  .ci/scripts/run-docs
  .github/workflows/run-readme-pr.yml
Labels: CLA Signed

#1439 Update run-docs to avoid code duplication
  .ci/scripts/run-docs
  .github/workflows/run-readme-pr-mps.yml
  README.md
  docs/quantization.md
  runner/run.cpp
  torchchat/quant_config/cuda-32.json
  torchchat/quant_config/mobile-32.json
Labels: CLA Signed

#1487 Update check_gibberish
  .ci/scripts/check_gibberish
Labels: CLA Signed, CI Infra, triaged
