Repository pytorch/torchchat, pull requests merged in 2025-02, with the labels that each got.

#1488 Add DeepSeek R1 Distill 8B
  README.md
  tokenizer/hf_tokenizer.py
  torchchat/model_config/models.json
  torchchat/model_params/DeepSeek-R1-Distill-Llama-8B.json
Labels: enhancement, CLA Signed, triaged

#1478 Enable sdpa backends for server export in export.py
  .github/workflows/more-tests.yml
  torchchat/export.py
Labels: CLA Signed

#1474 Decode_n_tokens yield eos/eot token
  torchchat/generate.py
Labels: CLA Signed

#1492 Update README.md
  README.md
Labels: CLA Signed

#1486 Update pull.yml to test snapshot saving and loading
  .github/workflows/pull.yml
Labels: CLA Signed

#1494 Info Message fix in cli.py
  torchchat/cli/cli.py
Labels: CLA Signed

#1495 Update test-tinystories-executorch: Disable config mobile-32, fix typo
  .github/workflows/pull.yml
Labels: CLA Signed, ExecuTorch, CI Infra, triaged

#1476 source instead of exec in run-readme-pr-macos.yml
  .ci/scripts/run-docs
  .github/workflows/run-readme-pr-linuxaarch64.yml
  .github/workflows/run-readme-pr-macos.yml
  .github/workflows/run-readme-pr-mps.yml
  .github/workflows/run-readme-pr.yml
  README.md
  docs/ADVANCED-USERS.md
  docs/multimodal.md
  docs/native-execution.md
  docs/quantization.md
Labels: CLA Signed, Compile / AOTI, CI Infra, triaged

#1505 Bump torchao pin closer to nightly: 2/26/2025
  install/install_requirements.sh
Labels: CLA Signed, Quantization, triaged

#1503 Add XPU support for AOT inductor
  install/install_requirements.sh
  torchchat/cli/builder.py
  torchchat/utils/build_utils.py
Labels: CLA Signed

#1507 Issue:1506 Add the min, max to embedding 4bit.
  torchchat/utils/quantize.py
Labels: CLA Signed
