Repository pytorch/torchchat, pull requests merged in 2025-04, with the labels that each got.

#1522 Bump ET Pin to 2025-3-5
  install/.pins/et-pin.txt
Labels: CLA Signed, ExecuTorch, triaged

#1523 Enable compile on MPS with experimental warning
  torchchat/cli/cli.py
  torchchat/generate.py
Labels: CLA Signed

#1524 Add Initial unit test example: Model_Config
  install/requirements.txt
  pytest.ini
  torchchat/model_config/tests/test_model_config.py
Labels: CLA Signed

#1527 [PyProject] Spin up an initial pyproject.toml allowing for local pip install
  install/install_requirements.sh
  install/install_torch.sh
  pyproject.toml
Labels: CLA Signed, triaged, Installing

#1528 Removing redundant installs from install_requirements.sh
  install/install_requirements.sh
Labels: CLA Signed, triaged

#1529 Bump PT pins to April 17th
  install/install_torch.sh
Labels: CLA Signed

#1531 mps compile: Bump PT pin to April 18th
  install/install_torch.sh
Labels: CLA Signed

#1521 Add Ascend NPU Support
  install/install_torch.sh
  torchchat/cli/builder.py
  torchchat/cli/cli.py
  torchchat/generate.py
  torchchat/utils/build_utils.py
  torchchat/utils/device_info.py
  torchchat/utils/quantize.py
Labels: CLA Signed

#1533 move just-in-time compilation time message
  torchchat/generate.py
Labels: CLA Signed

#1534 Accumulate tokens in generate mode
  torchchat/cli/cli.py
  torchchat/generate.py
Labels: CLA Signed
